### ISSUE TITLE
Chore: Migrate `elixir-auth-github-demo` App from `Heroku` to `Fly.io`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github-demo#22]
Sadly, all "free" Heroku Apps will be deleted this month ...  ref: https://github.com/dwyl/learn-heroku/issues/52 🤦‍♂️ 

# Todo

+ [x] Migrate app to `elixir-auth-github-demo.fly.dev` 
+ [x] Update deployment docs in `README.md`
+ [x] `DELETE` any files related to `Heroku` deployment
+ [x] Add GIF of working App 
+ [x] Update URL in repo settings 
+ [x] ***`DELETE`*** Heroku App! ✂️

**Comment by nelsonic** [comment]
Attempting to mock :httpoison` in the demo app's tests but getting the following error:

```
ERROR! the application :elixir_auth_github has a different value set for key :httpoison_mock during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was not set
  * Runtime value was set to: true

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile elixir_auth_github --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag



06:59:55.035 [error] Task #PID<0.235.0> started from #PID<0.95.0> terminating
** (stop) "aborting boot"
    (elixir 1.14.1) Config.Provider.boot/2
Function: &:erlang.apply/2
    Args: [#Function<1.104735216/1 in Mix.Tasks.Compile.All.load_apps/3>, [elixir_auth_github: "/Users/n/code/elixir-auth-github-demo/_build/test/lib"]]
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (ErlangError) Erlang error: "aborting boot"
        (elixir 1.14.1) Config.Provider.boot/2
```

Need to check how we're doing this in `auth` ... 🔍 ⏳

**Comment by nelsonic** [comment]
Appears to be working over in `auth`:
https://github.com/dwyl/auth/blob/bc1f8a9ca08ff26a4f7a50ef2e71bae4985d33d1/config/test.exs#L26-L29

# 🤷‍♂️

**Comment by nelsonic** [comment]
had to run:

```sh
MIX_ENV=test mix deps.compile elixir_auth_github --force
```

![image](https://user-images.githubusercontent.com/194400/206837506-9cf7bc94-3e47-45fd-9198-8fa1d96726cb.png)

**Comment by nelsonic** [comment]
## Waiting for machine to start... ⏳ 

```
Detected a Phoenix app
? Create .dockerignore from 2 .gitignore files? Yes
Created /Users/n/code/elixir-auth-github-demo/.dockerignore from 2 .gitignore files.
? Choose an app name (leave blank to generate one): elixir-auth-github-demo
? Select Organization: dwyl-elixir-auth-github-demo (dwyl-elixir-auth-github-demo)
? Choose a region for deployment: London, United Kingdom (lhr)
Created app elixir-auth-github-demo in organization dwyl-elixir-auth-github-demo
Admin URL: https://fly.io/apps/elixir-auth-github-demo
Hostname: elixir-auth-github-demo.fly.dev
Set secrets on elixir-auth-github-demo: SECRET_KEY_BASE
Preparing system for Elixir builds
Installing application dependencies
Running Docker release generator
Wrote config file fly.toml
? Would you like to set up a Postgresql database now? Yes
? Select configuration: Development - Single node, 1x shared CPU, 256MB RAM, 1GB disk
Creating postgres cluster in organization dwyl-elixir-auth-github-demo
Creating app...
Setting secrets on app elixir-auth-github-demo-db...
Provisioning 1 of 1 machines with image flyio/postgres:14.4
Waiting for machine to start...
```

**Comment by nelsonic** [comment]
I've read a few forum posts e.g: 
https://community.fly.io/t/fly-deploy-stuck-on-waiting-for-remote-builder/6768/35?page=2
https://community.fly.io/t/deploying-app-suddenly-takes-15-minutes/3705

Cannot escape from the "waiting" ...
Going to leave it here running in the background and keep working on something `else`...
but it's lame.

**Comment by nelsonic** [comment]
In a separate terminal window with the same `cwd`, running:

```sh
LOG_LEVEL=debug fly deploy
```

get: 
```sh
DEBUG {0x14001119710}
DEBUG <-- 200 https://api.fly.io/graphql (149.71ms)

{
  "data": {
    "finishBuild": {
      "id": "407491",
      "status": "failed",
      "wallclockTimeMs": 3330
    }
  }
}
Error failed to fetch an image or build from source: error building: failed to compute cache key: "/config/runtime.exs" not found: not found
```

**Comment by nelsonic** [comment]
```
cp ../mvp/config/runtime.exs ./config
```
# 🤞

**Comment by nelsonic** [comment]
https://fly.io/dashboard/dwyl-elixir-auth-github-demo
![image](https://user-images.githubusercontent.com/194400/206844131-3f979c38-bb4d-44c3-8fdd-43897fba270d.png)

**Comment by nelsonic** [comment]
```sh
Running release task (pending)... 🌎DEBUG --> POST https://api.fly.io/graphql

{
  "query": "query ($id: ID!) { releaseCommandNode: node(id: $id) { id ... on ReleaseCommand { id instanceId command status exitCode inProgress succeeded failed } } }",
  "variables": {
    "id": "rcmd_p98o26k8rwjz3ldm"
  }
}

DEBUG {}
Running release task (pending)... 🌏DEBUG <-- 200 https://api.fly.io/graphql (146.13ms)

{
  "data": {
    "releaseCommandNode": {
      "id": "rcmd_p98o26k8rwjz3ldm",
      "instanceId": "87b513f8",
      "command": "/app/bin/migrate",
      "status": "failed",
      "exitCode": null,
      "inProgress": false,
      "succeeded": false,
      "failed": true
    }
  }
}
DEBUG --> GET https://api.fly.io/api/v1/apps/elixir-auth-github-demo/logs?instance=87b513f8&next_token=

Error release command failed, deployment aborted
```

**Comment by nelsonic** [comment]
Ran:

```sh
mix phx.gen.release
```

ref: https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Release.html

**Comment by nelsonic** [comment]
```sh
flyctl postgres attach elixir-auth-github-demo-db -a elixir-auth-github-demo
```

Got:

```sh
Error no active leader found
```

DB not running: https://fly.io/apps/elixir-auth-github-demo-db

![image](https://user-images.githubusercontent.com/194400/206846203-1f9e53dd-af4f-4d74-bdc5-08573541f125.png)


Tried:
```sh
flyctl postgres restart -a elixir-auth-github-demo-db
```

Same error:
```sh
Error no active leader found
```

Going to delete the DB.

**Comment by nelsonic** [comment]
Deleted.
![image](https://user-images.githubusercontent.com/194400/206846934-bc978537-e21c-496c-83e9-f9b0d14e4a6e.png)

**Comment by nelsonic** [comment]
```
--> release v2 created

--> You can detach the terminal anytime without stopping the deployment
==> Release command detected: /app/bin/migrate

--> This release will not be available until the release command succeeds.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
	 2022/12/10 09:52:14 listening on [fdaa:0:fed6:a7b:7e:b0db:1ece:2]:22 (DNS: [fdaa::3]:53)
	 ERROR! Config provider Config.Reader failed with:
	 ** (RuntimeError) environment variable DATABASE_URL is missing.
	 {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,68,65,84,65,66,65,83,69,95,85,82,76,32,105,115,32,109,105,115,115,105,110,103,46,10,70,111,114,32,101,120,97,109,112,108,101,58,32,101,99,116,111,58,47,47,85,83,69,82,58,80,65,83,83,64,72,79,83,84,47,68,65,84,65,66,65,83,69,10>>},[{elixir_eval,'__FILE__',1,[{file,"/app/releases/1.6.3/runtime.exs"},{line,26}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,298},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,492}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,288}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,107}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,422}]}]}}
	 init terminating in do_boot ({,[{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,exprs,6,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]}]})
	 Crash dump is being written to: erl_crash.dump...done
	 Starting clean up.
Error release command failed, deployment aborted
```

**Comment by nelsonic** [comment]
Manually creating a new `postgres` instance.

**Comment by nelsonic** [comment]
```sh
fly postgres create
```

Name: `elixir-auth-github-demo-db`

Output:

```sh
? Choose an app name (leave blank to generate one): elixir-auth-github-demo-db
? Select Organization: dwyl-elixir-auth-github-demo (dwyl-elixir-auth-github-demo)
? Select region: Madrid, Spain (mad)
? Select configuration: Development - Single node, 1x shared CPU, 256MB RAM, 1GB disk
Creating postgres cluster in organization dwyl-elixir-auth-github-demo
Creating app...
Setting secrets on app elixir-auth-github-demo-db...
Provisioning 1 of 1 machines with image flyio/postgres:14.4
Waiting for machine to start...
Machine 6e8253dc742208 is created
==> Monitoring health checks
  Waiting for 6e8253dc742208 to become healthy (started, 2/3)
```

**Comment by nelsonic** [comment]
```sh
DEBUG {}
Running release task (pending)... 🌎DEBUG <-- 200 https://api.fly.io/graphql (143.11ms)

{
  "data": {
    "releaseCommandNode": {
      "id": "rcmd_l716z0knvwmymn80",
      "instanceId": "d61666ca",
      "command": "/app/bin/migrate",
      "status": "pending",
      "exitCode": null,
      "inProgress": true,
      "succeeded": false,
      "failed": false
    }
  }
}
Running release task (pending)... 🌍DEBUG --> POST https://api.fly.io/graphql

{
  "query": "query ($id: ID!) { releaseCommandNode: node(id: $id) { id ... on ReleaseCommand { id instanceId command status exitCode inProgress succeeded failed } } }",
  "variables": {
    "id": "rcmd_l716z0knvwmymn80"
  }
}

DEBUG {}
Running release task (pending)... 🌎DEBUG <-- 200 https://api.fly.io/graphql (141.91ms)

{
  "data": {
    "releaseCommandNode": {
      "id": "rcmd_l716z0knvwmymn80",
      "instanceId": "d61666ca",
      "command": "/app/bin/migrate",
      "status": "failed",
      "exitCode": null,
      "inProgress": false,
      "succeeded": false,
      "failed": true
    }
  }
}
DEBUG --> GET https://api.fly.io/api/v1/apps/elixir-auth-github-demo/logs?instance=d61666ca&next_token=

Error release command failed, deployment aborted
```

So basically this is failing because there's no migration ...
But we don't _need_ postgres for this app.
So I'm just going to re-create it from scratch!

**Comment by nelsonic** [comment]
https://elixir-auth-github-demo.fly.dev/
<img width="867" alt="image" src="https://user-images.githubusercontent.com/194400/218131112-d37f2a60-3457-4d06-9dea-d33f9d3d83cd.png">

🚀
